# SIVMC: Sila VM Connector API.
# Copyright 2019 The EVMC Authors.
# Licensed under the Apache License, Version 2.0.

[package]
name = "sivmc-vm"
version = "12.1.0"
authors = ["Alex Beregszaszi <alex@rtfs.hu>", "Jake Lang <jak3lang@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/sila-chain/sivmc"
description = "Bindings to SIVMC (VM specific)"
edition = "2018"

[dependencies]
sivmc-sys = { path = "../sivmc-sys", version = "12.1.0" }
